/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BukuController;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.table.DefaultTableModel;
import model.BukuData;

/**
 *
 * @author HanRey
 */
public class BukuForm extends javax.swing.JFrame {

    /**
     * Creates new form EmplyeeForm
     */
    //private Service service;
    private BukuController service;
    public BukuForm() {
        initComponents();
        //service = new Service();
        service = new BukuController();
        runTime();
    }
    private void runTime(){
        Timer t = new Timer();
        t.schedule(new TimerTask() {
            @Override
            public void run() {
                showData();
            }
        }, 0, 5000);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        bSave = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        tfJudul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(777, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Data Anggota");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 10, 150, 40);

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(350, 70, 340, 280);

        bSave.setText("SAVE");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        getContentPane().add(bSave);
        bSave.setBounds(40, 210, 80, 20);

        bUpdate.setText("UPDATE");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(bUpdate);
        bUpdate.setBounds(140, 210, 80, 23);

        bDelete.setText("DELETE");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bDelete);
        bDelete.setBounds(240, 210, 80, 23);
        getContentPane().add(tfJudul);
        tfJudul.setBounds(160, 120, 170, 30);

        jLabel3.setText("Judul Buku");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 120, 90, 30);
        getContentPane().add(tfId);
        tfId.setBounds(160, 70, 170, 30);

        jLabel2.setText("Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 70, 230, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 270, 110, 110);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // now save to temporary database
        service.save(getData());
        
        clear();
        // now we need  show data to table
        showData();
    }//GEN-LAST:event_bSaveActionPerformed
    private BukuData getData(){
        String id = tfId.getText();
        String judul = tfJudul.getText();
        
        // create Employee class
        BukuData e = new BukuData();
        e.setId(id);
        e.setJudulBuku(judul);

        return e;
    }
    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        service.update(getData());
        
        clear();
        showData();
    }//GEN-LAST:event_bUpdateActionPerformed

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        int iData = tableData.getSelectedRow();
        
        tfId.setText(tableData.getValueAt(iData, 0).toString());
        tfJudul.setText(tableData.getValueAt(iData, 1).toString());
        // get Valueat is getting data value on iData as row and next value is column
    }//GEN-LAST:event_tableDataMouseClicked

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        service.delete(getData());
        
        clear();
        showData();
    }//GEN-LAST:event_bDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Beranda().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    private void clear(){
        tfId.setText("");
        tfJudul.setText("");
    }
    private DefaultTableModel model;
    private void showData(){
        Object[] column = {"Id", "Judul Buku"};
        Object[][] data = new Object[service.getBuku().size()][2];
        // value 3 means much column on table
        for (int i = 0; i < service.getBuku().size(); i++) {
            BukuData e = service.getBuku().get(i);
            Object[] arr_data = {e.getId(), e.getJudulBuku()};
            data[i] = arr_data;
        }
        model = new DefaultTableModel(data, column);
        tableData.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bUpdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfJudul;
    // End of variables declaration//GEN-END:variables
}
