/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PengembalianController;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.table.DefaultTableModel;
import model.PengembalianData;


/**
 *
 * @author HanRey
 */
public class PengembalianForm extends javax.swing.JFrame {

    /**
     * Creates new form EmplyeeForm
     */
    //private Service service;
    private PengembalianController service;
    public PengembalianForm() {
        initComponents();
        //service = new Service();
        service = new PengembalianController();
        runTime();
    }
    private void runTime(){
        Timer t = new Timer();
        t.schedule(new TimerTask() {
            @Override
            public void run() {
                showData();
            }
        }, 0, 5000);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        bSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPeminjaman = new javax.swing.JTextField();
        tfPetugas = new javax.swing.JTextField();
        tfPengembalian = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(777, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Data Pengembalian");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 10, 240, 40);

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 60, 670, 200);

        bSave.setText("Input Pengembalian");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        getContentPane().add(bSave);
        bSave.setBounds(420, 320, 140, 20);

        jLabel2.setText("Id Peminjaman");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 280, 110, 14);

        jLabel3.setText("Tanggal pengembalian");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 280, 120, 14);

        jLabel4.setText("Id Petugas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 320, 60, 14);
        getContentPane().add(tfPeminjaman);
        tfPeminjaman.setBounds(180, 280, 80, 22);
        getContentPane().add(tfPetugas);
        tfPetugas.setBounds(180, 320, 80, 22);
        getContentPane().add(tfPengembalian);
        tfPengembalian.setBounds(490, 280, 80, 22);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(650, 270, 110, 110);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // now save to temporary database
        service.save(getData());
        
        clear();
        // now we need  show data to table
        showData();
    }//GEN-LAST:event_bSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Beranda().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    private PengembalianData getData(){
        String idPeminjaman = tfPeminjaman.getText();
        String idPetugas = tfPetugas.getText();
        String tanggalPengembalian = tfPengembalian.getText();
        
        // create Employee class
        PengembalianData e = new PengembalianData();
        e.setIdPeminjaman(idPeminjaman);
        e.setIdPetugas(idPetugas);
        e.setTanggalPengembalian(tanggalPengembalian);
        return e;
    }

    private void clear(){
        tfPeminjaman.setText("");
        tfPetugas.setText("");
        tfPengembalian.setText("");
    }
    private DefaultTableModel model;
    private void showData(){
        Object[] column = {"Id", "Nama", "Petugas", "Tgl_kembali", "Tgl_pengembalian"};
        Object[][] data = new Object[service.getPengembalian().size()][5];
        // value 3 means much column on table
        for (int i = 0; i < service.getPengembalian().size(); i++) {
            PengembalianData e = service.getPengembalian().get(i);
            Object[] arr_data = {e.getId(), e.getNama(), e.getPetugas(), e.getTanggalKembali(), e.getTanggalPengembalian()};
            data[i] = arr_data;
        }
        
        model = new DefaultTableModel(data, column);
        tableData.setModel(model);
    }
    

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField tfPeminjaman;
    private javax.swing.JTextField tfPengembalian;
    private javax.swing.JTextField tfPetugas;
    // End of variables declaration//GEN-END:variables
}
